# Generated by Django 2.1.7 on 2019-03-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCounters',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('num', models.IntegerField(default='0')),
                ('day', models.DateField()),
                ('id_customers', models.ForeignKey(on_delete='cascade', to='notification_service.Customers')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='notificationcounters',
            unique_together={('id', 'day')},
        ),
    ]
