# Generated by Django 2.1.7 on 2019-03-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_service', '0002_auto_20190302_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationcounters',
            name='id_customers',
            field=models.ForeignKey(null=True, on_delete='cascade', to='notification_service.Customers'),
        ),
    ]
