# Generated by Django 2.1.7 on 2019-03-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_service', '0003_auto_20190303_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationcounters',
            name='id_customers',
            field=models.ForeignKey(default=0, on_delete='cascade', to='notification_service.Customers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notifications',
            name='id_customer',
            field=models.ForeignKey(null=True, on_delete='cascade', to='notification_service.Customers'),
        ),
    ]
